apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 

resources:
  - ../base

namespace: default

patches:
- target:
    kind: Deployment
    name: my-nginx
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-nginx
    spec:
      replicas: 4
